namespace :shopping_cart do
  namespace :fill do
    desc 'Fill countries with default values'
    task countries: :environment do
      ShoppingCart::Country.delete_all
      ShoppingCart::Country.create(title:'Afghanistan')
      ShoppingCart::Country.create(title:'Albania')
      ShoppingCart::Country.create(title:'Algeria')
      ShoppingCart::Country.create(title:'Andorra')
      ShoppingCart::Country.create(title:'Angola')
      ShoppingCart::Country.create(title:'Antigua and Barbuda')
      ShoppingCart::Country.create(title:'Argentina')
      ShoppingCart::Country.create(title:'Armenia')
      ShoppingCart::Country.create(title:'Australia')
      ShoppingCart::Country.create(title:'Austria')
      ShoppingCart::Country.create(title:'Azerbaijan')
      ShoppingCart::Country.create(title:'Bahamas')
      ShoppingCart::Country.create(title:'Bahrain')
      ShoppingCart::Country.create(title:'Bangladesh')
      ShoppingCart::Country.create(title:'Barbados')
      ShoppingCart::Country.create(title:'Belarus')
      ShoppingCart::Country.create(title:'Belgium')
      ShoppingCart::Country.create(title:'Belize')
      ShoppingCart::Country.create(title:'Benin')
      ShoppingCart::Country.create(title:'Bhutan')
      ShoppingCart::Country.create(title:'Bolivia')
      ShoppingCart::Country.create(title:'Bosnia and Herzegovina')
      ShoppingCart::Country.create(title:'Botswana')
      ShoppingCart::Country.create(title:'Brazil')
      ShoppingCart::Country.create(title:'Brunei')
      ShoppingCart::Country.create(title:'Bulgaria')
      ShoppingCart::Country.create(title:'Burkina Faso')
      ShoppingCart::Country.create(title:'Burundi')
      ShoppingCart::Country.create(title:'Cabo Verde')
      ShoppingCart::Country.create(title:'Cambodia')
      ShoppingCart::Country.create(title:'Cameroon')
      ShoppingCart::Country.create(title:'Canada')
      ShoppingCart::Country.create(title:'Central African Republic (CAR)')
      ShoppingCart::Country.create(title:'Chad')
      ShoppingCart::Country.create(title:'Chile')
      ShoppingCart::Country.create(title:'China')
      ShoppingCart::Country.create(title:'Colombia')
      ShoppingCart::Country.create(title:'Comoros')
      ShoppingCart::Country.create(title:'Democratic Republic of the Congo')
      ShoppingCart::Country.create(title:'Republic of the Congo')
      ShoppingCart::Country.create(title:'Costa Rica')
      ShoppingCart::Country.create(title:'Croatia')
      ShoppingCart::Country.create(title:'Cuba')
      ShoppingCart::Country.create(title:'Cyprus')
      ShoppingCart::Country.create(title:'Czech Republic')
      ShoppingCart::Country.create(title:'Denmark')
      ShoppingCart::Country.create(title:'Djibouti')
      ShoppingCart::Country.create(title:'Dominica')
      ShoppingCart::Country.create(title:'Dominican Republic')
      ShoppingCart::Country.create(title:'Ecuador')
      ShoppingCart::Country.create(title:'Egypt')
      ShoppingCart::Country.create(title:'El Salvador')
      ShoppingCart::Country.create(title:'Equatorial Guinea')
      ShoppingCart::Country.create(title:'Eritrea')
      ShoppingCart::Country.create(title:'Estonia')
      ShoppingCart::Country.create(title:'Ethiopia')
      ShoppingCart::Country.create(title:'Fiji')
      ShoppingCart::Country.create(title:'Finland')
      ShoppingCart::Country.create(title:'France')
      ShoppingCart::Country.create(title:'Gabon')
      ShoppingCart::Country.create(title:'Gambia')
      ShoppingCart::Country.create(title:'Georgia')
      ShoppingCart::Country.create(title:'Germany')
      ShoppingCart::Country.create(title:'Ghana')
      ShoppingCart::Country.create(title:'Greece')
      ShoppingCart::Country.create(title:'Grenada')
      ShoppingCart::Country.create(title:'Guatemala')
      ShoppingCart::Country.create(title:'Guinea')
      ShoppingCart::Country.create(title:'Guinea-Bissau')
      ShoppingCart::Country.create(title:'Guyana')
      ShoppingCart::Country.create(title:'Haiti')
      ShoppingCart::Country.create(title:'Honduras')
      ShoppingCart::Country.create(title:'Hungary')
      ShoppingCart::Country.create(title:'Iceland')
      ShoppingCart::Country.create(title:'India')
      ShoppingCart::Country.create(title:'Indonesia')
      ShoppingCart::Country.create(title:'Iran')
      ShoppingCart::Country.create(title:'Iraq')
      ShoppingCart::Country.create(title:'Ireland')
      ShoppingCart::Country.create(title:'Israel')
      ShoppingCart::Country.create(title:'Italy')
      ShoppingCart::Country.create(title:'Jamaica')
      ShoppingCart::Country.create(title:'Japan')
      ShoppingCart::Country.create(title:'Jordan')
      ShoppingCart::Country.create(title:'Kazakhstan')
      ShoppingCart::Country.create(title:'Kenya')
      ShoppingCart::Country.create(title:'Kiribati')
      ShoppingCart::Country.create(title:'Kosovo')
      ShoppingCart::Country.create(title:'Kuwait')
      ShoppingCart::Country.create(title:'Kyrgyzstan')
      ShoppingCart::Country.create(title:'Laos')
      ShoppingCart::Country.create(title:'Latvia')
      ShoppingCart::Country.create(title:'Lebanon')
      ShoppingCart::Country.create(title:'Lesotho')
      ShoppingCart::Country.create(title:'Liberia')
      ShoppingCart::Country.create(title:'Libya')
      ShoppingCart::Country.create(title:'Liechtenstein')
      ShoppingCart::Country.create(title:'Lithuania')
      ShoppingCart::Country.create(title:'Luxembourg')
      ShoppingCart::Country.create(title:'Macedonia')
      ShoppingCart::Country.create(title:'Madagascar')
      ShoppingCart::Country.create(title:'Malawi')
      ShoppingCart::Country.create(title:'Malaysia')
      ShoppingCart::Country.create(title:'Maldives')
      ShoppingCart::Country.create(title:'Mali')
      ShoppingCart::Country.create(title:'Malta')
      ShoppingCart::Country.create(title:'Marshall Islands')
      ShoppingCart::Country.create(title:'Mauritania')
      ShoppingCart::Country.create(title:'Mauritius')
      ShoppingCart::Country.create(title:'Mexico')
      ShoppingCart::Country.create(title:'Micronesia')
      ShoppingCart::Country.create(title:'Moldova')
      ShoppingCart::Country.create(title:'Monaco')
      ShoppingCart::Country.create(title:'Mongolia')
      ShoppingCart::Country.create(title:'Montenegro')
      ShoppingCart::Country.create(title:'Morocco')
      ShoppingCart::Country.create(title:'Mozambique')
      ShoppingCart::Country.create(title:'Myanmar (Burma)')
      ShoppingCart::Country.create(title:'Namibia')
      ShoppingCart::Country.create(title:'Nauru')
      ShoppingCart::Country.create(title:'Nepal')
      ShoppingCart::Country.create(title:'Netherlands')
      ShoppingCart::Country.create(title:'New Zealand')
      ShoppingCart::Country.create(title:'Nicaragua')
      ShoppingCart::Country.create(title:'Niger')
      ShoppingCart::Country.create(title:'Nigeria')
      ShoppingCart::Country.create(title:'North Korea')
      ShoppingCart::Country.create(title:'Norway')
      ShoppingCart::Country.create(title:'Oman')
      ShoppingCart::Country.create(title:'Pakistan')
      ShoppingCart::Country.create(title:'Palau')
      ShoppingCart::Country.create(title:'Palestine')
      ShoppingCart::Country.create(title:'Panama')
      ShoppingCart::Country.create(title:'Papua New Guinea')
      ShoppingCart::Country.create(title:'Paraguay')
      ShoppingCart::Country.create(title:'Peru')
      ShoppingCart::Country.create(title:'Philippines')
      ShoppingCart::Country.create(title:'Poland')
      ShoppingCart::Country.create(title:'Portugal')
      ShoppingCart::Country.create(title:'Qatar')
      ShoppingCart::Country.create(title:'Romania')
      ShoppingCart::Country.create(title:'Russia')
      ShoppingCart::Country.create(title:'Rwanda')
      ShoppingCart::Country.create(title:'Saint Kitts and Nevis')
      ShoppingCart::Country.create(title:'Saint Lucia')
      ShoppingCart::Country.create(title:'Saint Vincent and the Grenadines')
      ShoppingCart::Country.create(title:'Samoa')
      ShoppingCart::Country.create(title:'San Marino')
      ShoppingCart::Country.create(title:'Sao Tome and Principe')
      ShoppingCart::Country.create(title:'Saudi Arabia')
      ShoppingCart::Country.create(title:'Senegal')
      ShoppingCart::Country.create(title:'Serbia')
      ShoppingCart::Country.create(title:'Seychelles')
      ShoppingCart::Country.create(title:'Sierra Leone')
      ShoppingCart::Country.create(title:'Singapore')
      ShoppingCart::Country.create(title:'Slovakia')
      ShoppingCart::Country.create(title:'Slovenia')
      ShoppingCart::Country.create(title:'Solomon Islands')
      ShoppingCart::Country.create(title:'Somalia')
      ShoppingCart::Country.create(title:'South Africa')
      ShoppingCart::Country.create(title:'South Korea')
      ShoppingCart::Country.create(title:'South Sudan')
      ShoppingCart::Country.create(title:'Spain')
      ShoppingCart::Country.create(title:'Sri Lanka')
      ShoppingCart::Country.create(title:'Sudan')
      ShoppingCart::Country.create(title:'Suriname')
      ShoppingCart::Country.create(title:'Swaziland')
      ShoppingCart::Country.create(title:'Sweden')
      ShoppingCart::Country.create(title:'Switzerland')
      ShoppingCart::Country.create(title:'Syria')
      ShoppingCart::Country.create(title:'Taiwan')
      ShoppingCart::Country.create(title:'Tajikistan')
      ShoppingCart::Country.create(title:'Tanzania')
      ShoppingCart::Country.create(title:'Thailand')
      ShoppingCart::Country.create(title:'Timor-Leste')
      ShoppingCart::Country.create(title:'Togo')
      ShoppingCart::Country.create(title:'Tonga')
      ShoppingCart::Country.create(title:'Trinidad and Tobago')
      ShoppingCart::Country.create(title:'Tunisia')
      ShoppingCart::Country.create(title:'Turkey')
      ShoppingCart::Country.create(title:'Turkmenistan')
      ShoppingCart::Country.create(title:'Tuvalu')
      ShoppingCart::Country.create(title:'Uganda')
      ShoppingCart::Country.create(title:'Ukraine')
      ShoppingCart::Country.create(title:'United Arab Emirates (UAE)')
      ShoppingCart::Country.create(title:'United Kingdom (UK)')
      ShoppingCart::Country.create(title:'United States of America (USA)')
      ShoppingCart::Country.create(title:'Uruguay')
      ShoppingCart::Country.create(title:'Uzbekistan')
      ShoppingCart::Country.create(title:'Vanuatu')
      ShoppingCart::Country.create(title:'Vatican City (Holy See)')
      ShoppingCart::Country.create(title:'Venezuela')
      ShoppingCart::Country.create(title:'Vietnam')
      ShoppingCart::Country.create(title:'Yemen')
      ShoppingCart::Country.create(title:'Zambia')
      ShoppingCart::Country.create(title:'Zimbabwe')
    end

    desc 'Fill deliveries with default values'
    task deliveries: :environment do
      ShoppingCart::Delivery.create(name:'Ukrposhta', cost:'2')
      ShoppingCart::Delivery.create(name:'Nova Poshta', cost:'10')
      ShoppingCart::Delivery.create(name:'Supermen Post', cost:'15')
    end

    desc 'Create coupon'
    task coupons: :environment do
      ShoppingCart::Coupon.create(name:'sale', discount:'10')
    end
  end
end